default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: visualizr_development
  username: postgres
  password: password
  host: localhost
  #schema_search_path: myapp,sharedapp,public

test:
  <<: *default
  database: visualizr_test

production:
  <<: *default
  database: visualizr_production
  username: visualizr
  password: <%= ENV['TASK-MANAGER-SPA_DATABASE_PASSWORD'] %>
